Lock requirejs-rails to 0.9.5 due to bug in 0.9.6
During deployment to Heroku,
`rake requirejs:precompile:all RAILS_ENV=production RAILS_GROUPS=assets`
fails with `NoMethodError: undefined method `[]' for nil:NilClass` due
to a breaking change in requirejs-rails 0.9.6.

The last time I updated the gem, I neglected to push to Heroku, and
therefore didn't know about this issue.

Deployment works fine with 0.9.5, so I'm reverting and locking it
there until a new requirejs-rails release comes out.

Closes #811.